### ISSUE TITLE
大佬，请问有论文的代码吗？跪求~

### ISSUE THREAD

**Issue by Summer-1994** [PengboLiu/NLP-Papers#1]

**Comment by PengboLiu** [comment]
要看是哪篇论文啊，有的有有的没有。

**Comment by Summer-1994** [comment]
1、Multi-Granularity Self-Attention for Neural Machine Translation
2、Self-Attention with Relative Position Representations
3、Self-Attention with Structural Position Representations
4、Syntax-Aware Aspect Level Sentiment Classification with Graph Attention Networks
5、CAN: Constrained Attention Networks for Multi-Aspect Sentiment Analysis
这几篇论文不知道哪个有？期待~
