### ISSUE TITLE
望求代码~

### ISSUE THREAD

**Issue by Summer-1994** [PengboLiu/NLP-Papers#2]
1、Multi-Granularity Self-Attention for Neural Machine Translation
2、Self-Attention with Relative Position Representations
3、Self-Attention with Structural Position Representations
4、Syntax-Aware Aspect Level Sentiment Classification with Graph Attention Networks
5、CAN: Constrained Attention Networks for Multi-Aspect Sentiment Analysis
这几篇论文不知道哪个有？谢谢~

**Comment by wulongfeng** [comment]
I can download for you if you still want it

**Comment by Summer-1994** [comment]
哇哇哇谢谢谢谢~

**Comment by wulongfeng** [comment]
给个邮箱吧

**Comment by Summer-1994** [comment]
858199137@qq.com
非常感谢

**Comment by wulongfeng** [comment]
done

**Comment by xyltt** [comment]
> 给个邮箱吧
I also want the codes of these papers. Could you please provide them for me? Thanks a lot! 
e-mail: palladiozt@gmail.com

**Comment by wwwang77** [comment]
> 给个邮箱吧

你好请问现在还可以发我一份代码吗？多谢了 1025482686@qq.com~

**Comment by wwwang77** [comment]
> [858199137@qq.com](mailto:858199137@qq.com)
> 非常感谢

你好请问代码可以转发我一份吗？ 1025482686@qq.com~  多谢了！

**Comment by Summer-1994** [comment]
呀不好意思我也没有找到(&gt;﹏<)



---原始邮件---
发件人: "wwwang77"<notifications@github.com&gt;
发送时间: 2020年6月2日(周二) 上午10:39
收件人: "PengboLiu/NLP-Papers"<NLP-Papers@noreply.github.com&gt;;
抄送: "Summer-1994"<858199137@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PengboLiu/NLP-Papers] 望求代码~ (#2)




  
858199137@qq.com
 非常感谢
  
你好请问代码可以转发我一份吗？ 1025482686@qq.com~  多谢了！

**Comment by Summer-1994** [comment]
亲我也没有找到(&gt;﹏<)



---原始邮件---
发件人: "wwwang77"<notifications@github.com&gt;
发送时间: 2020年6月2日(周二) 上午10:36
收件人: "PengboLiu/NLP-Papers"<NLP-Papers@noreply.github.com&gt;;
抄送: "Summer-1994"<858199137@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [PengboLiu/NLP-Papers] 望求代码~ (#2)




  
给个邮箱吧
  
你好请问现在还可以发我一份代码吗？多谢了

**Comment by wwwang77** [comment]
> 呀不好意思我也没有找到(&gt;﹏<)
> […](#)
> ---原始邮件--- 发件人: "wwwang77"<notifications@github.com&gt; 发送时间: 2020年6月2日(周二) 上午10:39 收件人: "PengboLiu/NLP-Papers"<NLP-Papers@noreply.github.com&gt;; 抄送: "Summer-1994"<858199137@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [PengboLiu/NLP-Papers] 望求代码~ (#2) 858199137@qq.com 非常感谢 你好请问代码可以转发我一份吗？ 1025482686@qq.com~ 多谢了！ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的麻烦了~
